import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Sampada Dhole',
  description: 'Generated by Sampada',
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning="true">
    <head />
    <body>
      <Providers>{children}</Providers>
    </body>
  </html>
  )
}
